### PR TITLE
Replace constant defines by static const typed variables

### PR DESCRIPTION
**Pull request by eliemichel**
This may be a naive question, but is there any reason for these constant values to be declared as macro variables using `#define` rather than typed static consts?

We already use static const for enum values now so there should be no support issue.

### CODE REVIEW

**Comment by eliemichel** [comment]
(Will update webgpu.yml and gen script if relevant)

**Comment by kainino0x** [comment]
None of us had strong opinions on which way to go, but it's a bit more traditional. It feels too arbitrary to be worth changing, but I don't know.

- for example gl.h and vulkan_core.h do it this way
- there was some preference for macros expressed here: https://github.com/webgpu-native/webgpu-headers/pull/34
- it also turns out there are some limitations with `static const` that might push us toward macros: https://github.com/webgpu-native/webgpu-headers/issues/339 (though I _don't think_ we'll use macros to define all of the flags constants - incidentally Vulkan also uses `static const` for 64-bit flags).

**Comment by kainino0x** [comment]
> * it also turns out there are some limitations with `static const` that might push us toward macros: [Latest header does not compile on MSVC due to const expressions #339](https://github.com/webgpu-native/webgpu-headers/issues/339) (though I _don't think_ we'll use macros to define all of the flags constants - incidentally Vulkan also uses `static const` for 64-bit flags).

I [checked](https://godbolt.org/z/GW5PjdTWK), and this applies to MSVC C but not C++. The pattern this will create problems for is e.g.:
```c
static const uint64_t kMyUsages = WGPUBufferUsage_CopyDst | WGPUBufferUsage_Uniform;
```
but users can deal with this, by themselves using a macro:
```c
#define MY_USAGES (WGPUBufferUsage_CopyDst | WGPUBufferUsage_Uniform)
```

**Comment by kainino0x** [comment]
I found a useful series of answers about C here: https://stackoverflow.com/questions/1674032/static-const-vs-define-vs-enum
(which was harder to find than the equivalent C++ question here: https://stackoverflow.com/questions/1637332/static-const-vs-define)

Given we probably don't get any significant type safety out of these (they're mostly uint32_t and they're no worse than `UINT32_MAX` etc.) I would lean weakly toward just keeping the `#defines`.

**Comment by kainino0x** [comment]
Dec 12 meeting:

* This is for the few sentinel values at the top of the file.  
* KN: Only concrete difference is that you can't make static consts from static consts. But that's not a big deal.  
* ?: Avoids possibly taking up memory on bad compilers.
* LK: Seems fine to keep \#defines  
* CF: Can just let fancier languages use fancier constants.  
* **Leave as is**

**Pull request closed without merging**
