### PR TITLE
Remove Fence in favor of QueueOnSubmittedWorkDone

### PR DESCRIPTION
**Pull request by Kangz**
This has a signaledValue argument contrary to the current WebGPU spec in
preparation for it being added in the future when WebGPU gains
multi-queue support. For now it should be invalid to pass any value other
than 0, when QueueSignal is added, 0 should mean "the latest signaled
value".

### CODE REVIEW

**Comment by kvark** [comment]
You are pushing for delaying multi-queue (which is totally reasonable to delay!), and at the same time trying to get the API in here before we get it? Are you trying to reduce the future breakage for people?

**Comment by Kangz** [comment]
Exactly! We cannot do overloads in C so adding the signal value now is to avoid having two different functions in the C API when we add multi-queue.

**Review by kvark — APPROVED** [review]
okie-dokie

**Comment by Kangz** [comment]
Thanks, @kainino0x @austinEng WDYT?

**Review by austinEng — APPROVED** [review]
Looks good.

It will be interesting to design how Signal is going to work eventually. The old way we used to have it doesn't look like it would let you read the last signaled value and signal a new value, all atomically.

**Review by kainino0x — APPROVED** [review]

**Comment by Kangz** [comment]
Yeah we should revisit this when we try to stabilize webgpu.h to make sure it is in line with the future idea for multi-queue. Thanks all!

**Pull request merged**
