### PR TITLE
Adds WGPUBool typedef.

### PR DESCRIPTION
**Pull request by lokokung**
#84

### CODE REVIEW

**Review by kainino0x — COMMENTED** [review]
Any reason not to bundle with the other changes to remove stdbool.h and usages of `bool`?

**Comment by lokokung** [comment]
Whoops, no, there's no reason it wasn't included. Updated now!

**Review by Beyley — APPROVED** [review]
looks good from my end! should help smooth out bindings from C# (since `bool` in C# is generally marshalled as a 32-bit type for compat with the windows BOOL type, see [this page](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.unmanagedtype?view=net-7.0) UnmanagedType.Bool is 32-bit)

**Review by kainino0x — APPROVED** [review]
LGTM!

**Pull request merged**
