### PR TITLE
timestampWrites is an array in JS. It needs a count 

### PR DESCRIPTION
**Pull request by Andersbakken**

### CODE REVIEW

**Comment by Kangz** [comment]
It seems like it isn't? See the idl below.

```webidl
dictionary GPUComputePassDescriptor
         : [GPUObjectDescriptorBase](https://gpuweb.github.io/gpuweb/#dictdef-gpuobjectdescriptorbase) {
    [GPUComputePassTimestampWrites](https://gpuweb.github.io/gpuweb/#dictdef-gpucomputepasstimestampwrites) [timestampWrites](https://gpuweb.github.io/gpuweb/#dom-gpucomputepassdescriptor-timestampwrites);
};

dictionary GPUComputePassTimestampWrites {
    required GPUQuerySet querySet;
    GPUSize32 beginningOfPassWriteIndex;
    GPUSize32 endOfPassWriteIndex;
};
```

**Comment by beaufortfrancois** [comment]
@Kangz is right. See a JS example at https://developer.chrome.com/blog/new-in-webgpu-121#timestamp_queries_in_compute_and_render_passes

**Comment by Kangz** [comment]
Tentatively closing.

**Comment by kainino0x** [comment]
I think it used to be an array, but indeed now it is just a nullable sub-structure.

**Comment by Andersbakken** [comment]
Ah. My bad.

Sorry about that.

regards

Anders

**Pull request closed without merging**
