### PR TITLE
Add WGPUSurfaceDescriptorFromXcbWindow

### PR DESCRIPTION
**Pull request by rajveermalviya**
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkXcbSurfaceCreateInfoKHR.html

### CODE REVIEW

**Comment by Kangz** [comment]
LGTM although I don't think it will be possible to use it with OpenGL ES because AFAIK EGL only supports X11 windows and not XCB windows. (and you can't convert XCB -> X11 window). That could be fine.

@kvark or @cwfitzgerald WDYT for wgpu?

**Comment by rajveermalviya** [comment]
as per [this](https://www.phoronix.com/scan.php?page=news_item&px=Mesa-21.0-EGL_EXT_platform_xcb) & [this](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/6474) mesa drivers support it since 21.0, no idea about nvidia though.

**Comment by cwfitzgerald** [comment]
Seems we only support X11 and wayland https://github.com/gfx-rs/wgpu/blob/master/wgpu-hal/src/gles/egl.rs#L563-L569

**Comment by cwfitzgerald** [comment]
Ah yeah, that should be fine, it matches what we get from raw-window-handle https://docs.rs/raw-window-handle/latest/raw_window_handle/struct.XcbHandle.html

**Comment by Kangz** [comment]
Great!

**Pull request merged**
